import { PDFDocument, StandardFonts, rgb } from "pdf-lib"

const MARGIN = 60
const PAGE_WIDTH = 595   // A4
const PAGE_HEIGHT = 842  // A4
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2
const LINE_HEIGHT = 16
const FONT_SIZE = 10
const HEADING_SIZE = 14

/** Wrap text into lines that fit within maxWidth at the given font size */
function wrapText(text: string, font: Awaited<ReturnType<PDFDocument["embedFont"]>>, size: number, maxWidth: number): string[] {
  const lines: string[] = []
  for (const paragraph of text.split("\n")) {
    if (paragraph.trim() === "") {
      lines.push("")
      continue
    }
    const words = paragraph.split(" ")
    let current = ""
    for (const word of words) {
      const candidate = current ? `${current} ${word}` : word
      if (font.widthOfTextAtSize(candidate, size) <= maxWidth) {
        current = candidate
      } else {
        if (current) lines.push(current)
        current = word
      }
    }
    if (current) lines.push(current)
  }
  return lines
}

export async function generateSignedContractPdf({
  orgName,
  adopterName,
  animalName,
  contractText,
  typedSignature,
  signedAt,
  signerIp,
  contractHash,
}: {
  orgName: string
  adopterName: string
  animalName: string
  contractText: string
  typedSignature: string
  signedAt: Date
  signerIp: string
  contractHash: string
}): Promise<Uint8Array> {
  const doc = await PDFDocument.create()
  const fontRegular = await doc.embedFont(StandardFonts.Helvetica)
  const fontBold = await doc.embedFont(StandardFonts.HelveticaBold)

  const dark = rgb(0.1, 0.22, 0.16)   // #1a3a2a-ish
  const black = rgb(0.1, 0.1, 0.1)
  const grey = rgb(0.45, 0.45, 0.45)
  const lightGrey = rgb(0.85, 0.85, 0.85)

  function addPage() {
    const p = doc.addPage([PAGE_WIDTH, PAGE_HEIGHT])
    // Header bar
    p.drawRectangle({ x: 0, y: PAGE_HEIGHT - 48, width: PAGE_WIDTH, height: 48, color: dark })
    p.drawText("CARA", { x: MARGIN, y: PAGE_HEIGHT - 31, size: 14, font: fontBold, color: rgb(0.29, 0.87, 0.5) })
    p.drawText("Adoption Contract", { x: MARGIN + 54, y: PAGE_HEIGHT - 31, size: 12, font: fontRegular, color: rgb(1, 1, 1) })
    // Footer
    p.drawLine({ start: { x: MARGIN, y: 40 }, end: { x: PAGE_WIDTH - MARGIN, y: 40 }, thickness: 0.5, color: lightGrey })
    p.drawText(`${orgName}  ·  Generated by Cara`, { x: MARGIN, y: 26, size: 8, font: fontRegular, color: grey })
    p.drawText(`Page ${doc.getPageCount()}`, { x: PAGE_WIDTH - MARGIN - 30, y: 26, size: 8, font: fontRegular, color: grey })
    return p
  }

  let page = addPage()
  let y = PAGE_HEIGHT - 72  // start below header

  function ensureSpace(needed: number) {
    if (y - needed < 55) {
      page = addPage()
      y = PAGE_HEIGHT - 72
    }
  }

  function drawLine(text: string, opts: { bold?: boolean; size?: number; color?: ReturnType<typeof rgb>; indent?: number } = {}) {
    const size = opts.size ?? FONT_SIZE
    const font = opts.bold ? fontBold : fontRegular
    const color = opts.color ?? black
    const x = MARGIN + (opts.indent ?? 0)
    ensureSpace(size + 4)
    if (text) {
      page.drawText(text, { x, y, size, font, color })
    }
    y -= LINE_HEIGHT
  }

  function drawBlank(n = 1) {
    y -= LINE_HEIGHT * n
  }

  // Title
  drawBlank(0.5)
  drawLine("ADOPTION AGREEMENT", { bold: true, size: HEADING_SIZE, color: dark })
  drawBlank(0.5)

  // Meta block
  const metaLines = [
    `Shelter:  ${orgName}`,
    `Adopter:  ${adopterName}`,
    `Animal:   ${animalName}`,
    `Date:     ${signedAt.toLocaleDateString("en-IE", { day: "2-digit", month: "long", year: "numeric" })}`,
  ]
  // Light box
  ensureSpace(metaLines.length * LINE_HEIGHT + 20)
  page.drawRectangle({ x: MARGIN, y: y - metaLines.length * LINE_HEIGHT - 6, width: CONTENT_WIDTH, height: metaLines.length * LINE_HEIGHT + 16, color: rgb(0.97, 0.97, 0.97), borderColor: lightGrey, borderWidth: 0.5 })
  y -= 4
  for (const l of metaLines) drawLine(l, { size: 10, indent: 8 })
  drawBlank(1.5)

  // Contract body
  const bodyLines = wrapText(contractText, fontRegular, FONT_SIZE, CONTENT_WIDTH)
  for (const line of bodyLines) {
    ensureSpace(LINE_HEIGHT)
    if (line) {
      page.drawText(line, { x: MARGIN, y, size: FONT_SIZE, font: fontRegular, color: black })
    }
    y -= LINE_HEIGHT
  }

  drawBlank(2)

  // Signature block
  ensureSpace(160)
  page.drawRectangle({ x: MARGIN, y: y - 130, width: CONTENT_WIDTH, height: 140, color: rgb(0.97, 0.99, 0.97), borderColor: rgb(0.7, 0.85, 0.7), borderWidth: 0.8 })
  y -= 8

  drawLine("ELECTRONIC SIGNATURE", { bold: true, size: 10, color: dark, indent: 8 })
  drawBlank(0.5)
  drawLine("Signed by (typed name):", { size: 9, color: grey, indent: 8 })
  drawLine(typedSignature, { bold: true, size: 13, color: dark, indent: 8 })
  drawBlank(0.5)
  drawLine(`Signed at:  ${signedAt.toISOString()}`, { size: 9, color: grey, indent: 8 })
  drawLine(`IP address: ${signerIp}`, { size: 9, color: grey, indent: 8 })
  drawLine(`Doc SHA-256: ${contractHash}`, { size: 8, color: grey, indent: 8 })
  drawBlank(0.5)
  drawLine("This document was signed electronically. By typing their name above, the signatory", { size: 8, color: grey, indent: 8 })
  drawLine("agreed these details constitute a valid electronic signature under eIDAS Regulation", { size: 8, color: grey, indent: 8 })
  drawLine("(EU) No 910/2014. The SHA-256 hash above identifies the exact document text that was signed.", { size: 8, color: grey, indent: 8 })

  const bytes = await doc.save()
  return bytes
}
